import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { env } from '../config/env.js';

export const PDF_CONTENT_TYPE = 'application/pdf';

function gold() {
  return rgb(0.79, 0.64, 0.15);
}

function navy() {
  return rgb(0.04, 0.11, 0.2);
}

async function brandedPdf(title: string, lines: string[]) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]);
  const font = await pdf.embedFont(StandardFonts.TimesRoman);
  const bold = await pdf.embedFont(StandardFonts.TimesRomanBold);
  page.drawRectangle({ x: 0, y: 800, width: 595.28, height: 42, color: navy() });
  page.drawText('GYAN CHOWK', { x: 48, y: 814, size: 14, font: bold, color: gold() });
  page.drawText(title, { x: 48, y: 750, size: 22, font: bold, color: navy() });
  let y = 710;
  for (const line of lines) {
    page.drawText(line, { x: 48, y, size: 12, font, color: navy() });
    y -= 20;
  }
  page.drawText(env.NEXT_PUBLIC_APP_URL, { x: 48, y: 48, size: 10, font, color: gold() });
  return Buffer.from(await pdf.save());
}

export async function invoicePdf(input: {
  invoiceNumber: string;
  studentName: string;
  studentEmail: string;
  productLabel: string;
  amountPaise: number;
  gateway: string;
  issuedAt: Date;
}) {
  const amount = `INR ${(input.amountPaise / 100).toFixed(2)}`;
  return brandedPdf('TAX INVOICE', [
    `Invoice: ${input.invoiceNumber}`,
    `Date: ${input.issuedAt.toLocaleDateString('en-IN')}`,
    `Billed to: ${input.studentName} (${input.studentEmail})`,
    `Item: ${input.productLabel}`,
    `Gateway: ${input.gateway}`,
    `Amount paid: ${amount}`,
    'This invoice is generated by Gyan Chowk after payment verification.',
  ]);
}

export async function certificatePdf(input: {
  certificateId: string;
  studentName: string;
  courseTitle: string;
  issuedAt: Date;
}) {
  return brandedPdf('CERTIFICATE OF COMPLETION', [
    `This is to certify that`,
    input.studentName,
    `has successfully completed`,
    input.courseTitle,
    `Certificate ID: ${input.certificateId}`,
    `Issued: ${input.issuedAt.toLocaleDateString('en-IN')}`,
    'Verify this certificate on the Gyan Chowk public verify page.',
  ]);
}

export async function resumePdf(input: {
  name: string;
  contact?: { email?: string; phone?: string; location?: string };
  education?: Array<{ school: string; detail?: string; year?: string }>;
  skills?: string[];
  experience?: Array<{ title: string; org?: string; detail?: string }>;
  projects?: Array<{ name: string; detail?: string }>;
}) {
  const lines = [
    input.contact?.email ?? '',
    input.contact?.phone ?? '',
    input.contact?.location ?? '',
    '',
    'Education',
    ...(input.education ?? []).map((e) => `${e.year ?? ''} ${e.school}${e.detail ? ` — ${e.detail}` : ''}`),
    '',
    `Skills: ${(input.skills ?? []).join(', ')}`,
    '',
    'Experience',
    ...(input.experience ?? []).map((e) => `${e.title}${e.org ? ` @ ${e.org}` : ''}${e.detail ? ` — ${e.detail}` : ''}`),
    '',
    'Projects',
    ...(input.projects ?? []).map((p) => `${p.name}${p.detail ? ` — ${p.detail}` : ''}`),
  ].filter((line, i, arr) => !(line === '' && arr[i - 1] === ''));
  return brandedPdf(input.name || 'Resume', lines);
}
