export default {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        gyan: {
          primary: 'var(--gyan-primary)',
          'primary-light': 'var(--gyan-primary-light)',
          'primary-dark': 'var(--gyan-primary-dark)',
          secondary: 'var(--gyan-secondary)',
          'secondary-light': 'var(--gyan-secondary-light)',
          'secondary-dark': 'var(--gyan-secondary-dark)',
          accent: 'var(--gyan-accent)',
          background: 'var(--gyan-background)',
          'background-secondary': 'var(--gyan-background-secondary)',
          surface: 'var(--gyan-surface)',
          text: 'var(--gyan-text)',
          'text-secondary': 'var(--gyan-text-secondary)',
          muted: 'var(--gyan-text-muted)',
          border: 'var(--gyan-border)',
          'border-hover': 'var(--gyan-border-hover)',
          success: 'var(--gyan-success)',
          warning: 'var(--gyan-warning)',
          error: 'var(--gyan-error)',
          info: 'var(--gyan-info)',
          footer: 'var(--gyan-footer)',
        },
        gc: {
          black: 'var(--gyan-text)',
          navy: 'var(--gyan-background-secondary)',
          ink: 'var(--gyan-surface)',
          panel: 'var(--gyan-background-secondary)',
          line: 'var(--gyan-border)',
          blue: 'var(--gyan-accent)',
          glow: 'var(--gyan-accent)',
          gold: 'var(--gyan-gold)',
          amber: 'var(--gyan-gold)',
          orange: 'var(--gyan-accent)',
          mist: 'var(--gyan-text-secondary)',
          mute: 'var(--gyan-text-muted)',
          surface: 'var(--gyan-surface)',
        },
      },
      fontFamily: {
        sans: ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'ui-serif', 'Georgia', 'serif'],
      },
      boxShadow: {
        glow: '0 18px 40px color-mix(in srgb, var(--gyan-primary-dark) 10%, transparent)',
        gold: '0 8px 20px color-mix(in srgb, var(--gyan-secondary) 18%, transparent)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      backgroundImage: {
        'gc-hero':
          'linear-gradient(180deg, #ffffff 0%, var(--gyan-background) 100%)',
        'gyan-cta': 'linear-gradient(180deg, #171717 0%, #0a0a0a 100%)',
      },
    },
  },
  plugins: [],
};
